    
name: Testes de API

on:
  push:
    branches:
      - master

jobs:
  teste-de-api-com-serverest-local-em-docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
    - name: Setup do Node.js
      uses: actions/setup-node@v2
    - name: Acessar diretório da aplicação e Instalar as dependências do projeto
      run: cd meet-api && npm i
    - name: Executar os testes de API
      run: npm test